### ISSUE TITLE
Using unet to train/test custom dataset

### ISSUE THREAD

**Issue by gopi77** [jakeret/tf_unet#101]
Hi

I understand from section 3 of https://arxiv.org/pdf/1505.04597.pdf that for training we need input train/validation images along with segmentation maps.
I couldn't be able to find these image files (jpg?) in the demo of toy problem & radio data. (are they kept in special formats?)

Is there any sample training/validation/test images with segmentation maps available in a well defined folder structure along with example code to understand the training/testing steps.
So that once we understand the dataset definition/usage it will be easy to replace those files with our own dataset & train.

Regards
Gopi. J

**Comment by jakeret** [comment]
In the toy example the data is generated on the fly, meaning that there are no jpegs or so. For the radio data there is a notebook showing how to produce the training data.
If your data is imaging data you can use the [`ImageDataProvider`](http://tf-unet.readthedocs.io/en/latest/tf_unet.html#tf_unet.image_util.ImageDataProvider)

**Comment by gopi77** [comment]
Hi
Thanks for the input. I tried the below code.

from tf_unet.image_util import ImageDataProvider
from tf_unet import unet

data_provider = ImageDataProvider

[gp_train.tar.gz](https://github.com/jakeret/tf_unet/files/1308277/gp_train.tar.gz)


('gp_train/*')
net = unet.Unet(channels=data_provider.channels, 
                n_class=data_provider.n_class
                )

trainer = unet.Trainer(net, optimizer="momentum", opt_kwargs=dict(momentum=0.2))
path = trainer.train(data_provider, './train_out',
                     training_iters=32, 
                     epochs=1, 
                     dropout=0.5, 
                     display_step=2)

And the error is :>>>

InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-14-c90474b24912> in <module>()
      5                      epochs=1,
      6                      dropout=0.5,
----> 7                      display_step=2)
      8 

/home/gopi/dksh/tf_unet/tf_unet/unet.pyc in train(self, data_provider, output_path, training_iters, epochs, dropout, display_step, restore, write_graph)
    403 
    404             test_x, test_y = data_provider(self.verification_batch_size)
--> 405             pred_shape = self.store_prediction(sess, test_x, test_y, "_init")
    406 
    407             summary_writer = tf.summary.FileWriter(output_path, graph=sess.graph)

/home/gopi/dksh/tf_unet/tf_unet/unet.pyc in store_prediction(self, sess, batch_x, batch_y, name)
    449         loss = sess.run(self.net.cost, feed_dict={self.net.x: batch_x, 
    450                                                        self.net.y: util.crop_to_shape(batch_y, pred_shape),
--> 451                                                        self.net.keep_prob: 1.})
    452 
    453         logging.info("Verification error= {:.1f}%, loss= {:.4f}".format(error_rate(prediction,

/home/gopi/.local/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in run(self, fetches, feed_dict, options, run_metadata)
    787     try:
    788       result = self._run(None, fetches, feed_dict, options_ptr,
--> 789                          run_metadata_ptr)
    790       if run_metadata:
    791         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/home/gopi/.local/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _run(self, handle, fetches, feed_dict, options, run_metadata)
    995     if final_fetches or final_targets:
    996       results = self._do_run(handle, final_targets, final_fetches,
--> 997                              feed_dict_string, options, run_metadata)
    998     else:
    999       results = []

/home/gopi/.local/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1130     if handle is None:
   1131       return self._do_call(_run_fn, self._session, feed_dict, fetch_list,
-> 1132                            target_list, options, run_metadata)
   1133     else:
   1134       return self._do_call(_prun_fn, self._session, handle, feed_dict,

/home/gopi/.local/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _do_call(self, fn, *args)
   1150         except KeyError:
   1151           pass
-> 1152       raise type(e)(node_def, op, message)
   1153 
   1154   def _extend_graph(self):

InvalidArgumentError: logits and labels must be same size: logits_size=[1140224,2] labels_size=[1142400,2]
	 [[Node: SoftmaxCrossEntropyWithLogits = SoftmaxCrossEntropyWithLogits[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"](Reshape_31, Reshape_32)]]

Caused by op u'SoftmaxCrossEntropyWithLogits', defined at:
  File "/home/gopi/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/gopi/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/gopi/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/home/gopi/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/gopi/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 474, in start
    ioloop.IOLoop.instance().start()
  File "/home/gopi/anaconda2/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/home/gopi/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py", line 887, in start
    handler_func(fd_obj, events)
  File "/home/gopi/anaconda2/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/gopi/anaconda2/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/home/gopi/anaconda2/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/gopi/anaconda2/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/home/gopi/anaconda2/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/gopi/anaconda2/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 276, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/gopi/anaconda2/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/gopi/anaconda2/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 390, in execute_request
    user_expressions, allow_stdin)
  File "/home/gopi/anaconda2/lib/python2.7/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/gopi/anaconda2/lib/python2.7/site-packages/ipykernel/zmqshell.py", line 501, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/gopi/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/gopi/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2821, in run_ast_nodes
    if self.run_code(code, result):
  File "/home/gopi/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-13-8f0b163f4700>", line 4, in <module>
    n_class=data_provider.n_class
  File "/home/gopi/dksh/tf_unet/tf_unet/unet.py", line 191, in __init__
    self.cost = self._get_cost(logits, cost, cost_kwargs)
  File "/home/gopi/dksh/tf_unet/tf_unet/unet.py", line 229, in _get_cost
    labels=flat_labels))
  File "/home/gopi/.local/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 1594, in softmax_cross_entropy_with_logits
    precise_logits, labels, name=name)
  File "/home/gopi/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 2380, in _softmax_cross_entropy_with_logits
    features=features, labels=labels, name=name)
  File "/home/gopi/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/gopi/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/gopi/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): logits and labels must be same size: logits_size=[1140224,2] labels_size=[1142400,2]
	 [[Node: SoftmaxCrossEntropyWithLogits = SoftmaxCrossEntropyWithLogits[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"](Reshape_31, Reshape_32)]]

------------------------

Inside the folder gp_train, I have 20 train & mask images in tif format.
Both having resolution 565 (width) x 584 (height) 
Ex: file names:
21.tif
21_mask.tif   

Attached sample files for reference.
[gp_train.tar.gz](https://github.com/jakeret/tf_unet/files/1308280/gp_train.tar.gz)


Regards
Gopi. J

**Comment by jakeret** [comment]
There is a bug in the code which causes this error if one side of input image has an odd number of pixels (565). See other related issues for that

**Comment by gopi77** [comment]
ok, Please update after the bug fix.

**Comment by monicakapadia** [comment]
Which dataset used?
