### ISSUE TITLE
Error with example code

### ISSUE THREAD

**Issue by asaydin** [jakeret/tf_unet#21]
I am having trouble running the code provided in the usage section (http://tf-unet.readthedocs.io/en/latest/usage.html)

I created a folder named images and placed my .jpg files in that folder. Here is my code: 

```
from tf_unet import unet, util, image_util

#preparing data loading
data_provider = image_util.ImageDataProvider("images/*.jpg")

#setup & training
net = unet.Unet(layers=3, features_root=64, channels=1, n_class=2)
trainer = unet.Trainer(net)

output_path = "train/"

path = trainer.train(data_provider, output_path, training_iters=32, epochs=100)

#verification
#...

prediction = net.predict(path, data)

unet.error_rate(prediction, util.crop_to_shape(label, prediction.shape))

img = util.combine_img_prediction(data, label, prediction)
util.save_image(img, "prediction.jpg")

```
And here is the error message: 

```
[aaydin@sn-nvda3 unet_test]$ python test.py 
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
Number of files used: 100
2017-03-07 07:54:16,681 Layers 3, features 64, filter size 3x3, pool size: 2x2
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    path = trainer.train(data_provider, output_path, training_iters=32, epochs=100)
  File "/gpfs/home/aaydin/tf_unet/tf_unet/unet.py", line 386, in train
    init = self._initialize(training_iters, output_path, restore)
  File "/gpfs/home/aaydin/tf_unet/tf_unet/unet.py", line 345, in _initialize
    self.optimizer = self._get_optimizer(training_iters, global_step)
  File "/gpfs/home/aaydin/tf_unet/tf_unet/unet.py", line 321, in _get_optimizer
    **self.opt_kwargs).minimize(self.net.cost, 
TypeError: __init__() takes at least 3 arguments (2 given)
```

It looks like this is not related to my code. It should have something to do with tf-unet.

**Comment by jakeret** [comment]
Looks like that the Tensorflow API changed a little. I just pushed a change that should adress that. Let me know if it helps

**Comment by jakeret** [comment]
I'm assuming that this is resolved
