### ISSUE TITLE
ValueError: could not broadcast input array from shape (500,333,3) into shape (375,500,3)

### ISSUE THREAD

**Issue by panovr** [jakeret/tf_unet#38]
The error is:

> Traceback (most recent call last):
>   File "my_unet.py", line 12, in <module>
>     path = trainer.train(data_provider, "./unet_trained", training_iters=20, epochs=10, display_step=2)
>   File "/usr/local/lib/python2.7/dist-packages/tf_unet-0.1.0-py2.7.egg/tf_unet/unet.py", line 399, in train
>     test_x, test_y = data_provider(self.verification_batch_size)
>   File "/usr/local/lib/python2.7/dist-packages/tf_unet-0.1.0-py2.7.egg/tf_unet/image_util.py", line 98, in __call__
>     X[i] = train_data
> ValueError: could not broadcast input array from shape (500,333,3) into shape (375,500,3)

I have validated that the dimension of color image and corresponding mask is same for all.

numpy version:  1.12.1
tensorflow version: 1.0.1

**Comment by panovr** [comment]
Maybe all images need to have the same dimension? I resize all images and masks to the same dimension, and this error got resolved.
