### ISSUE TITLE
NiiImageDataProvider: Generic data provider for nifti images.

### ISSUE THREAD

**Issue by EdwardMa12593** [jakeret/tf_unet#50]
Thanks for shearing the tf_unet code and it is an excellent work.
I want to train the unet with custom nifti image data. Each data is a three-dimensional volume data.

I failed to use the SimpleDataProvider and ImageDataProvider class. 
So, I **try to write 'NiiImageDataProvider' to read nifti data and train the unet.**
Following is ***NiiImageDataProvider class*** code, It can correctly read the nifti data in local path.
**However, when training the unet,  I get an error in `__call__` function.**
I don't know how to modify this function. I'll appreciate a lot if anyone can help me fix it.
Here are my [data and code](https://drive.google.com/open?id=0B90vBrSuhLbJQnZScGw5NUl0YlE)

```python
import nibabel as nb
class NiiImageDataProvider(BaseDataProvider):
    """
    This is an introduction to NiiImageDataProvider (similar to ImageDataProvider provided by jakeret)
    Generic data provider for nifti images.
    Assumes that the data images and label images are stored in the same folder
    and that the labels have a different file prefix 
    e.g. 'demo/data-1.nii' and 'demo/data-label-1.nii'

    Usage:
    data_provider = image_util.NiiImageDataProvider("../tf_unet-master/demo/*.nii")

    :param nii_path: a glob search pattern to find all data and label images
    :param a_min: (optional) min value used for clipping
    :param a_max: (optional) max value used for clipping
    :param Nii_data_prefix: prefix pattern for the data images. Default 'data-*.nii'
    :param Nii_Label_prefix: prefix pattern for the label images. Default 'data-label-*.nii'

    """

    channels = 1
    n_class = 2
    def __init__(self, nii_path, a_min=None, a_max=None, Nii_data_prefix="data", Nii_Label_prefix='data-label'):
        super(NiiImageDataProvider, self).__init__(a_min, a_max)
        self.Nii_data_prefix = Nii_data_prefix
        self.Nii_Label_prefix = Nii_Label_prefix
        self.file_idx = -1

        self.nii_data_files = self._find_niidata_files(nii_path)
        print(nii_path)

        assert len(self.nii_data_files) > 0, "No nii training data"
        print("Number of files used: %s" % len(self.nii_data_files))

        img = self._load_nii_file(self.nii_data_files[0])
        img = img.get_data() # get 3-dimension image data in nifti image
        self.channels = 1 if len(img.shape) == 3 else img.shape[-1]

    def _find_niidata_files(self, nii_path):
        all_niifiles = glob.glob(nii_path)
        return [name for name in all_niifiles if not self.Nii_Label_prefix in name]

    def _load_nii_file(self, path):
        return nb.load(path)

    def _cylce_nii_file(self):
        self.file_idx += 1
        if self.file_idx >= len(self.nii_data_files):
            self.file_idx

    def _next_data(self):
        self._cylce_nii_file()
        nii_image_name = self.nii_data_files[self.file_idx]
        nii_label_name = nii_image_name.replace(self.Nii_data_prefix, self.Nii_Label_prefix)

        nii_image = self._load_nii_file(nii_image_name)
        nii_image = nii_image.get_data()
        nii_image = nii_image.transpose(2, 0, 1)
        nz = nii_image.shape[0]
        nii_image = nii_image.reshape(nz, 512, 512, 1)

        nii_label = self._load_nii_file(nii_label_name)
        nii_label = nii_label.get_data()
        nii_label[nii_label == 2] = 1
        nii_label = nii_label.transpose(2, 0, 1)
        nii_label = nii_label.reshape(nz, 512, 512, 1)


        return nii_image, nii_label
```
**Test code:**
```python
from tf_unet import unet
from tf_unet import image_util
# read data
data_provider = image_util.NiiImageDataProvider("X:/tf_unet-master/test_nii_provider/*.nii")
# set parameter
net = unet.Unet(channels=1, n_class=3, layers=3, features_root=16)
trainer = unet.Trainer(net, optimizer="momentum", opt_kwargs=dict(momentum=0.2))
# train
path = trainer.train(data_provider, "./seg_3dim_data_trained_0509", training_iters=5, epochs=1, display_step=2)
```

**Error:**
```python
Traceback (most recent call last):
  File "G:/Tensorflow/tf_unet-master/test_nii_provider/test_nii_provider.py", line 9, in <module>
    path = trainer.train(data_provider, "./seg_3dim_data_trained_0509", training_iters=5, epochs=1, display_step=2)
  File "G:\Tensorflow\tf_unet-master\tf_unet\unet.py", line 403, in train
    test_x, test_y = data_provider(self.verification_batch_size)
  File "G:\Tensorflow\tf_unet-master\tf_unet\image_util.py", line 98, in __call__
    train_data, labels = self._load_data_and_label()
  File "G:\Tensorflow\tf_unet-master\tf_unet\image_util.py", line 58, in _load_data_and_label
    return train_data.reshape(1, ny, nx, self.channels), labels.reshape(1, ny, nx, self.n_class),
ValueError: cannot reshape array of size 19398656 into shape (1,74,512,1)
```

**Comment by jakeret** [comment]
Not sure what is happening here `nii_label = nii_label.reshape(nz, 512, 512, 1)`. Shouldn't you simply return an array of shape `[512, 512, 1]`?
