### ISSUE TITLE
Loading a saved model?

### ISSUE THREAD

**Issue by carsnwd** [jakeret/tf_unet#80]
Hello,

I'm a bit confused on how loading saved models works after training. It doesn't help too much that TensorFlow seems to have changed this procedure multiple times as I found out from reading around haha. I've read this issue posted [here ](https://github.com/jakeret/tf_unet/issues/49 )and looked around a little. Doing just..

```
with tf.Session() as sess:
    net = unet.Unet(layers=3, features_root=32, channels=3, n_class=2)
    net.restore(sess, './unet_trained')
    print("Worked")
```
Has not worked for me, I get an error of `RuntimeError: The Session graph is empty.  Add operations to the graph before calling run().`

I tried other ideas from reading around such as...

```
with tf.Graph().as_default() as g:
    with tf.Session() as sess:
        net = unet.Unet(layers=3, features_root=32, channels=3, n_class=2)
        net.restore(sess, './unet_trained')
        print("Worked")
```

But still same result. I looked at the demos such as the radio one, and it loads just a single model.cpkt file, but I can't find that in my unet_trained folder, just a model.cpkt.index, model.spkt.data-00000-of00001 and model.cpkt.meta

I found other ways to try and load the model in the `def restore` function such like...

```
        # saver = tf.train.Saver()
        saver = tf.train.import_meta_graph(model_path+'/model.cpkt.meta')
        saver.restore(sess, model_path)
        logging.info("Model restored from file: %s" % model_path)
```

But no luck,

My other thought is maybe I'm not loading unet correctly. I thought these two lines...

```
        net = unet.Unet(layers=3, features_root=32, channels=3, n_class=2)
        net.restore(sess, './unet_trained')
```

Would just load a blank net and the restore our model to it was the idea.

Any help? Thanks for all the support.

**Comment by jakeret** [comment]
Have a look at the models [`predict` ](http://tf-unet.readthedocs.io/en/latest/tf_unet.html#tf_unet.unet.Unet.predict) function on how to load the model correctly.

You should also check the path that you pass to the function. The `trainer` instance returns a path that looks something like [this ](https://github.com/jakeret/tf_unet/blob/master/tf_unet/unet.py#L387)

**Comment by YJonmo** [comment]
Hi there,

Help please, I get error when I am trying to load a trained network. For the training I used 
tensorflow/1.5.0-gpu-k40-foss-2018a-python-3.6.4

for loading and doing the prediction I am using:
tensorflow/1.6.0rc1-foss-2018a/lib/python3.6


prediction = net.predict('./Results_ACL/model.ckpt.meta', image_test)
INFO:tensorflow:Restoring parameters from ./Results_ACL/model.ckpt.meta
2019-02-27 12:09:04,755 Restoring parameters from ./Results_ACL/model.ckpt.meta
2019-02-27 12:09:11.855034: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./Results_ACL/model.ckpt.meta: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
2019-02-27 12:09:13.955048: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./Results_ACL/model.ckpt.meta: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
2019-02-27 12:09:13.955087: W tensorflow/core/framework/op_kernel.cc:1202] OP_REQUIRES failed at save_restore_tensor.cc:170 : Data loss: Unable to open table file ./Results_ACL/model.ckpt.meta: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
Traceback (most recent call last):
  File "/pkg/suse12/software/tensorflow/1.6.0rc1-foss-2018a/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1361, in _do_call
    return fn(*args)
  File "/pkg/suse12/software/tensorflow/1.6.0rc1-foss-2018a/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1340, in _run_fn
    target_list, status, run_metadata)
  File "/pkg/suse12/software/tensorflow/1.6.0rc1-foss-2018a/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file ./Results_ACL/model.ckpt.meta: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
	 [[Node: save_22/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save_22/Const_0_0, save_22/RestoreV2/tensor_names, save_22/RestoreV2/shape_and_slices)]]

During handling of the above exception, another exception occurred:
.
.
.
