### ISSUE TITLE
fixed minibatch loss after trainning and question about prediction

### ISSUE THREAD

**Issue by MikeXlYang** [jakeret/tf_unet#88]
Hi jakeret, 
   Thx for the work. I'm training a set of rgb pictures with my gpu. In the begining it all went on well, but later in the process minibatch loss stays around 0.6931 while all other parameter went on well. 

`
2017-08-22 23:27:21,059 Iter 947, Minibatch Loss= 0.0900, Training Accuracy= 0.9480, Minibatch error= 5.2%
2017-08-22 23:27:24,957 Iter 948, Minibatch Loss= 0.3945, Training Accuracy= 0.8989, Minibatch error= 10.1%
2017-08-22 23:27:28,808 Iter 949, Minibatch Loss= 0.3875, Training Accuracy= 0.8581, Minibatch error= 14.2%
2017-08-22 23:27:32,554 Iter 950, Minibatch Loss= 0.6931, Training Accuracy= 0.7385, Minibatch error= 26.1%
2017-08-22 23:27:36,612 Iter 951, Minibatch Loss= 0.6931, Training Accuracy= 0.8400, Minibatch error= 16.0%
2017-08-22 23:27:40,259 Iter 952, Minibatch Loss= 0.6931, Training Accuracy= 0.8742, Minibatch error= 12.6%
2017-08-22 23:27:43,971 Iter 953, Minibatch Loss= 0.6931, Training Accuracy= 0.8700, Minibatch error= 13.0%
2017-08-22 23:27:47,618 Iter 954, Minibatch Loss= 0.6931, Training Accuracy= 0.9042, Minibatch error= 9.6%
`
And after a epoch it says:
`2017-08-22` 23:30:47,516 Verification error= 15.2%, loss= 0.6931
G:\Unet\tf_unet\tf_unet\util.py:74: RuntimeWarning: invalid value encountered in true_divide
  img /= `np.amax(img)`
For all iters later it just stayed fixed.

And beside this one. I don't know how to use the predict funtion correctly. It says the data shape should be[n, nx, ny, channels]. I used data=np.array(Image.open(path1), dtype), but it turned out to be a two-dimensional matrix which doesn't fit the function. If I have a set of new images, how can I use my trained `models`

I'm new to deeping learning and python so these maybe simple questions. Thanks for any help anyone is going to offer.

Here is my code.
`from tf_unet import unet, util, image_util
data_provider = image_util.ImageDataProvider("G:\\Unet\\tiff_512\\trainBatch1\\*.tif")
net = unet.Unet(layers=3, features_root=64, channels=3, n_class=2)
trainer = unet.Trainer(net)
output_path="G:\\Unet\\tf_unet\\trained_segment_unet_color_gpu2"
path = trainer.train(data_provider, output_path, training_iters=200, epochs=20)`

**Comment by MikeXlYang** [comment]
When I tried again, another problem occured 
2017-08-23 17:06:15,900 Restoring parameters from G:\Unet\tf_unet\trained_segment_unet_copy\model.cpkt
Traceback (most recent call last):

  File "E:\python\ana3\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py", line 2879, in run_code
    self.showtraceback(running_compiled_code=True)

  File "E:\python\ana3\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py", line 1811, in showtraceback
    self._showtraceback(etype, value, stb)

  File "E:\python\ana3\envs\tensorflow\lib\site-packages\ipykernel\zmqshell.py", line 554, in _showtraceback
    dh.parent_header, ident=topic)

  File "E:\python\ana3\envs\tensorflow\lib\site-packages\jupyter_client\session.py", line 730, in send
    to_send = self.serialize(msg, ident)

  File "E:\python\ana3\envs\tensorflow\lib\site-packages\jupyter_client\session.py", line 625, in serialize
    content = self.pack(content)

  File "E:\python\ana3\envs\tensorflow\lib\site-packages\jupyter_client\session.py", line 103, in <lambda>
    ensure_ascii=False, allow_nan=False,

  File "E:\python\ana3\envs\tensorflow\lib\site-packages\zmq\utils\jsonapi.py", line 43, in dumps
    s = s.encode('utf8')

UnicodeEncodeError: 'utf-8' codec can't encode character '\udcd5' in position 2808: surrogates not allowed

**Comment by jakeret** [comment]
The `RuntimeWarning` tend to show up when the gradients explode i.e. the training is not converging properly. Have you experimented with another cost function? Maybe you need some preprocessing of the images.

If you are using RGB image `data=np.array(Image.open(path1), dtype)` should be at least a 3d matrix otherwise something is not quite right. Then you can simply do `data[np.nexaxis, ...]` to turn it into a 4d tensor

As for `UnicodeEncodeError`: this is something I haven't seen before. I never ran the code on Windows
