### ISSUE TITLE
Questions of a noob

### ISSUE THREAD

**Issue by LauraLaureus** [jakeret/tf_unet#94]
Hello everyone. 
I'm quite noob at tensorflow and unet. 
I have been training unet for three days and My computer is not the best computation beast you can find in the market so I would like to have the chance to retrieve the results of the unet to use it in other code.

How can i do this?

Thank you for your time everyone.

**Comment by jakeret** [comment]
`tf_unet` stores the intermediate model checkpoints under the `output_path`. You should be able to reload the tf graph from there

**Comment by LauraLaureus** [comment]
I have my computer busy right now but i will be something like:

with tf.Session() as sess:
    unet.restore(sess,path)

(?)

**Comment by jakeret** [comment]
Sounds about right

**Comment by reshu-b7** [comment]
Hi everyone,
I am also very new to u-net and tensorflow in general. And, I have been trying to train and test the prediction for a Tiff format RGB image having 1600 + frames. I am using the basic code provided on the documentation page http://tf-unet.readthedocs.io/en/latest/usage.html

```
from tf_unet import unet, util, image_util

data_provider = image_util.ImageDataProvider(r"/home/reshubisht/Pictures/train/1_train.tif","r")
net = unet.Unet(layers=3, features_root=64, channels=1, n_class=4)
trainer = unet.Trainer(net)
path = trainer.train(data_provider, "/home/reshubisht/Pictures/test/", training_iters=32, epochs=100)
data= image_util.ImageDataProvider(r"/home/reshubisht/Pictures/train/1_test.tif","r")
prediction = net.predict(path, data)
unet.error_rate(prediction, util.crop_to_shape(label, prediction.shape))
img = util.combine_img_prediction(data, label, prediction)
util.save_image(img, "/home/reshubisht/Pictures/prediction.jpg") 
```

But I am getting several different errors (after this particular command **path = trainer.train(data_provider, "/home/reshubisht/Pictures/test/", training_iters=32, epochs=100)** ) while trying to run the entire snippet. It would be great if you can clarify some of my doubts regarding the same.

- Do we need to provide an image mask along with the training image, or the code generates it itself. I asked it as I got errors that the code was searching for a mask in the root directory of the project.
- Is the above mentioned code enough to perform training and prediction or do we need to add some lines. It looks pretty complete to me.
- With the above written code, I am currently getting the following error after  **path = trainer.train(data_provider, "/home/reshubisht/Pictures/test/", training_iters=32, epochs=100)**
```

>>> path = trainer.train(data_provider, "/home/reshubisht/Pictures/test/", training_iters=32, epochs=100)
2017-09-08 23:30:30,086 Removing '/home/reshubisht/prediction'
2017-09-08 23:30:30,162 Removing '/home/reshubisht/Pictures/test'
2017-09-08 23:30:30,185 Allocating '/home/reshubisht/prediction'
2017-09-08 23:30:30,185 Allocating '/home/reshubisht/Pictures/test'
2017-09-08 23:30:30.186204: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-08 23:30:30.186229: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-08 23:30:30.186238: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-09-08 23:30:30.186246: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-08 23:30:30.186256: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "/home/reshubisht/.local/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
TypeError: ufunc 'maximum' did not contain a loop with signature matching types dtype('<U32') dtype('<U32') dtype('<U32')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/reshubisht/.local/lib/python3.5/site-packages/tf_unet-0.1.0-py3.5.egg/tf_unet/unet.py", line 404, in train
    test_x, test_y = data_provider(self.verification_batch_size)
  File "/home/reshubisht/.local/lib/python3.5/site-packages/tf_unet-0.1.0-py3.5.egg/tf_unet/image_util.py", line 87, in __call__
    train_data, labels = self._load_data_and_label()
  File "/home/reshubisht/.local/lib/python3.5/site-packages/tf_unet-0.1.0-py3.5.egg/tf_unet/image_util.py", line 49, in _load_data_and_label
    train_data = self._process_data(data)
  File "/home/reshubisht/.local/lib/python3.5/site-packages/tf_unet-0.1.0-py3.5.egg/tf_unet/image_util.py", line 72, in _process_data
    data = np.clip(np.fabs(data), self.a_min, self.a_max)
  File "/home/reshubisht/.local/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 1727, in clip
    return _wrapfunc(a, 'clip', a_min, a_max, out=out)
  File "/home/reshubisht/.local/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 67, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/home/reshubisht/.local/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 47, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
TypeError: ufunc 'maximum' did not contain a loop with signature matching types dtype('<U32') dtype('<U32') dtype('<U32')
```

**Comment by LauraLaureus** [comment]
I have problems trying to resore. Somewhere in tensorflow the permission changes and cannot open the file.
Any ideas @jakeret ? 

`
net = unet.Unet(channels=channels,
                    n_class=n_class, 
                    layers=3, 
                    features_root=16,
                    cost="dice_coefficient")

sess = tf.Session()

net.restore(sess,model_path = "./unet_trained")`

**Comment by jakeret** [comment]
Hmm thats something I haven't seen before
