### ISSUE TITLE
Error running demo_radio_data.ipynb

### ISSUE THREAD

**Issue by gopi77** [jakeret/tf_unet#98]
Running the line 3 of demo_radio_data.ipynb in jupyter notebook gives error.
!seek --file-prefix='./bgs_example_data' --post-processing-prefix='bgs_example_data/seek_cache' --chi-1=20 --overwrite=True seek.config.process_survey_fft
sh: 1: seek: not found

Anyone faced/solved this?, Please let me know.

My PC details:
OS: Ubuntu 16.04
tensorflow 1.2.1
Python 2.7.13 |Anaconda custom (64-bit)| (default, Dec 20 2016, 23:09:15)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2

Regards
Gopi. J

**Comment by jakeret** [comment]
HIDE&SEEK are two packages from here: https://github.com/cosmo-ethz

**Comment by gopi77** [comment]
Installed seek as per http://seek.readthedocs.io/en/latest/installation.html

But got another error while executing !seek --file-prefix='./bgs_example_data' --post-processing-prefix='bgs_example_data/seek_cache' --chi-1=20 --overwrite=True seek.config.process_survey_fft

Traceback (most recent call last):
  File "/home/gopi/.local/bin/seek", line 11, in <module>
    load_entry_point('seek==0.1.0', 'console_scripts', 'seek')()
  File "/home/gopi/anaconda2/lib/python2.7/site-packages/ivy/cli/main.py", line 28, in run
    _main(*sys.argv[1:])
  File "/home/gopi/anaconda2/lib/python2.7/site-packages/ivy/cli/main.py", line 37, in _main
    mgr.launch()
  File "/home/gopi/anaconda2/lib/python2.7/site-packages/ivy/workflow_manager.py", line 107, in launch
    executor.run(ctx().params.plugins)
  File "/home/gopi/anaconda2/lib/python2.7/site-packages/ivy/backend.py", line 48, in run
    return map(LoopWrapper(loop), mapPlugin.getWorkload())
  File "/home/gopi/anaconda2/lib/python2.7/site-packages/ivy/backend.py", line 126, in __call__
    for plugin in self.loop:
  File "/home/gopi/anaconda2/lib/python2.7/site-packages/ivy/loop.py", line 95, in next
    return self._instantiate(plugin)
  File "/home/gopi/anaconda2/lib/python2.7/site-packages/ivy/loop.py", line 136, in _instantiate
    return PluginFactory.createInstance(pluginName, self.ctx)
  File "/home/gopi/anaconda2/lib/python2.7/site-packages/ivy/plugin/plugin_factory.py", line 48, in createInstance
    raise UnsupportedPluginTypeException("Module '%s' could not be loaded" % pluginName, ex)
ivy.exceptions.exceptions.UnsupportedPluginTypeException: (u"Module 'seek.plugins.initialize' could not be loaded", ImportError('/home/gopi/anaconda2/lib/python2.7/site-packages/healpy/_healpy_sph_transform_lib.so: undefined symbol: GOMP_parallel',))

**Comment by gopi77** [comment]
Below command helped :)
conda install libgcc
